version: '3'

volumes:
    mongo_volume:

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_volume:/data/db



  
  lottery:
    image: lottery
    restart: always
    depends_on:
      - 'mongodb'
    ports:
      - '8080:8080'
    

  
  

  
 
